dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # UI & Effects
  flutter_slidable: ^3.0.1
  fl_chart: ^0.66.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3

  # Optional
  table_calendar: ^3.0.9
